services:
  tag:
    build: .
    container_name: tag-app
    restart: always
    ports:
      - 80:80
      - 433:433
      - 9001:9001
    expose:
      - 80
    networks:
      - tag-v3-network
    environment:
      HOST_DB_TAG: 'mysql'
      USER_DB_TAG: 'root'
      PWD_DB_TAG: 'root'
      YII_DEBUG: 1
      PHP_ENABLE_XDEBUG: 1
      SEDSP_URL: "https://homologacaointegracaosed.educacao.sp.gov.br"
    volumes:
      - .:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /app/docker/mysql
      - /app/vendor
      - /app/app/vendor
      - /app/assets
      - /app/db
      - /app/.git
      # - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    expose:
      - 3306
    deploy:
        resources:
            limits:
              cpus: '2'
              memory: 1024M
            reservations:
              cpus: '1'
              memory: 1GB
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: tag
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
      # - .\dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./dump-data.sql:/docker-entrypoint-initdb.d/dump-data.sql
    networks:
      - tag-v3-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - tag-v3-network

networks:
  tag-v3-network:

volumes:
  db-volume:


